apiVersion: batch/v1
kind: Job
metadata:
  name: local-volume-updater
  labels:
    app: local-volume-updater
spec:
  backoffLimit: 5
  template:
    spec:
      serviceAccountName: local-storage-update
      restartPolicy: Never
      containers:
      - name: updater
        image: registry.k8s.io/sig-storage/local-volume-update-pv-to-beta:latest
        env:
        # If you want provisioner to use a kubeconfig file to access API server, instead of the default
              #  in-cluster config, then specify the following environment variable:
              # - name: KUBECONFIG
              #   value: /path/to/kubeconfig
      restartPolicy: OnFailure
